version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 4000
    environment:
      MESSAGE: Docker
    ports:
      - 4000:4000
    command: npm start
